spring:
  datasource:
    username: root
    password: Vasant1990*
    url:  jdbc:mysql://localhost:3306/spwosidb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kattavasant@gmail.com
    password: kattavenugopal
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
            
 
  